In [1]:
using LinearAlgebra

include("../src/tebd.jl")
using .TimeEvolvingBlockDecimation
using .TimeEvolvingBlockDecimation.MatrixProductState

Let's initialize a 12 qubit state in the $|0\cdots0\rangle$ state. Normally we would work with the representation 
$$|\psi\rangle=\left(\begin{matrix}
    1\\
    0\\
    0\\
    \vdots\\
    0
\end{matrix}\right)$$
with $$|\psi\rangle\in C^{\left(2^{12}\right)}$$
But instead we'll expand the tensor products implicit in $$|00\cdots0\rangle=|0\rangle\otimes|0\rangle\otimes\cdots$$ explicitly by writing out the full tensor. In other words we will instead use
    $$|\psi\rangle\in C^{2\times2\times\cdots\times2}$$
    with
    $$(|\psi\rangle)_{00\cdots0}=1.$$

In [2]:
sites = 12
ψ = zeros((2 for _=1:sites)...)
ψ[(1 for _=1:sites)...] = 1;

Now we convert $|\psi\rangle$ into an MPS:

In [3]:
ψ_mps = mps(ψ);

With this representation, it is much less constly to apply local operators to the state $|\psi\rangle$. Instead of calculating the matrix exponential $e^{-i\hat{H}t}$ using the full hamiltonian $\hat{H}$, we can apply one- or two-local operators at each site in the chain, reinforce the maximum allowed bond dimension, and repeat for each site or pair of sites that is included in $\hat{H}$.

In [4]:
# Define Pauli basis and tensor product shorthand.
# Use t=π/6 for this example.
⊗ = kron
I = [1 0; 0 1]
σ_x = [0 1; 1 0]
σ_y = [0 -1im; 1im 0]
σ_z = [1 0; 0 -1]

t = π / 6;

First, let's calculate the time-evolved state
$$|\psi(t)\rangle = exp\left\{-i\hat{H}t\right\}|\psi\rangle,$$
where the Hamiltonian
$$\hat{H}=\sum_i\sigma_x^{(i)}$$
is a time-independent sum of single-qubit operators. The extremely naive method to calculate $|\psi(t)\rangle$ is to first calculate the matrix exponential, then do a matrix-vector multiplication. Let's do it this way first:

In [5]:
# The not as fast way

# Helper function for calculating H. We only use local terms in this example.
function ising_matrix(sites::Integer, local_only::Bool = false)
        I = [
            1 0
            0 1
        ]
        identity_string = [I for _ = 1:sites]
        local_term = zeros(2^sites, 2^sites)
        interaction_term = zeros(2^sites, 2^sites)

        for i = 1:sites
            pauli_string = copy(identity_string)
            pauli_string[i] = σ_x
            local_term += reduce(kron, pauli_string)
        end

        for i = 1:sites-1
            pauli_string = copy(identity_string)
            pauli_string[i] = σ_z
            pauli_string[i+1] = σ_z
            interaction_term += reduce(kron, pauli_string)
        end
        if local_only
            return local_term
        end
        return interaction_term + local_term
end

# Only use local terms for H:
H = ising_matrix(sites, true)
ψ_vect = zeros(2^sites)
ψ_vect[1] = 1

# Naive method: do the matrix exponential followed by a matrix-vector multiplication.
@time ψ_res_vect = exp(H * t * -1im) * ψ_vect

 24.743324 seconds (6.68 M allocations: 4.726 GiB, 0.96% gc time, 7.56% compilation time)


4096-element Vector{ComplexF64}:
    0.17797851562499956 + 0.0im
                    0.0 - 0.10275594390606246im
                    0.0 - 0.10275594390606206im
   -0.05932617187500035 + 0.0im
                    0.0 - 0.10275594390606241im
   -0.05932617187500032 + 0.0im
   -0.05932617187500048 + 0.0im
                    0.0 + 0.034251981302021194im
                    0.0 - 0.10275594390606213im
  -0.059326171875000305 + 0.0im
  -0.059326171875000305 + 0.0im
                    0.0 + 0.03425198130202117im
  -0.059326171875000416 + 0.0im
                        ⋮
                    0.0 - 0.001268591900074864im
 -0.0007324218750000013 + 0.0im
 -0.0007324218750000011 + 0.0im
                    0.0 + 0.0004228639666916218im
                    0.0 - 0.001268591900074864im
 -0.0007324218750000008 + 0.0im
  -0.000732421875000001 + 0.0im
                    0.0 + 0.00042286396669162214im
  -0.000732421875000001 + 0.0im
                    0.0 + 0.000422863966691622im
                    

Thanks to the `@time` macro, we can see that this calculation takes about 20 seconds and uses a whole lot of memory. Pretty bad. Alternatively, let's use block evolution on a MPS representation of $|\psi\rangle$. With this method, we only do twelve $2\times2$ matrix-vector multiplications, and since our initial state was unentangled the result is exact. Where our initial state (or system Hamiltonian) more highly entangled (entangling) the MPS representation (block evolution) would do a poorer job approximating the full matrix multiplication.

In [6]:
# The fast way
local_only_ising = Hamiltonian(0 * (σ_z ⊗ σ_z), σ_x)
@time ψ_res = reshape(contract_mps(block_evolve(ψ_mps, local_only_ising, t * -1im)), 2^sites)

  2.155233 seconds (8.01 M allocations: 436.644 MiB, 99.47% compilation time)


4096-element Vector{ComplexF64}:
      0.1779785156250009 - 7.705139889271523e-35im
  -4.448564589214635e-35 - 0.10275594390606424im
  -1.689546579027104e-35 - 0.10275594390606424im
    -0.05932617187500025 + 9.754601722097095e-36im
   7.323680981525651e-35 - 0.10275594390606425im
    -0.05932617187500026 - 4.228329186142776e-35im
   -0.059326171875000264 - 1.605902076541324e-35im
  -9.271679961833121e-36 + 0.034251981302021395im
  -4.448564589214636e-35 - 0.10275594390606424im
    -0.05932617187500025 + 2.568379963090506e-35im
    -0.05932617187500025 + 9.754601722097097e-36im
  5.6318219300903436e-36 + 0.03425198130202139im
    -0.05932617187500027 - 4.2283291861427763e-35im
                         ⋮
   9.041581458673635e-37 - 0.0012685919000748663im
  -0.0007324218750000026 - 5.22015948906515e-37im
  -0.0007324218750000027 - 1.982595156223855e-37im
 -1.1446518471398905e-37 + 0.0004228639666916218im
  -5.492055048413126e-37 - 0.001268591900074866im
  -0.0007324218750000024 + 3.17083

To prove the two results are equal:

In [7]:
dot(ψ_res_vect, ψ_res)

1.0000000000000018 - 1.2379560085042535e-34im

Let's switch to a full Ising model. Now
$$\hat{H}=\sum_{i=1}^{N-1}\sigma_z^{(i)}\sigma_z^{(i+1)}+J\sum_{i=1}^N\sigma_x^{(i)}$$
where $J$ tunes the relative strength of the transverse field. For this example we set $J=1.$

Since now $\hat{H}$ generates entanglement, the fidelity of the block-evolved state will not be as high as $t$ grows.

In [11]:
# The not as fast way
t = π/18
# Set H to the full ising matrix as above:
H = ising_matrix(sites, false)
ψ_vect = zeros(2^sites)
ψ_vect[1] = 1

# Naive method: do the matrix exponential followed by a matrix-vector multiplication.
@time ψ_res_vect = exp(H * t * -1im) * ψ_vect

 21.482188 seconds (40 allocations: 3.875 GiB, 0.62% gc time)


4096-element Vector{ComplexF64}:
    -0.3168174574843962 - 0.7755259603361564im
   -0.14364874560133256 + 0.030584965000867288im
    -0.1444270503942686 + 0.004587782983301147im
  0.0023264866112235757 + 0.0256878843715555im
   -0.14438166572085126 + 0.004600242805783457im
 -0.0036929732425348112 + 0.025062856024926063im
 -0.0022625234387036843 + 0.02554451715454213im
   0.004524743920254005 + 0.00013207642052309092im
   -0.14438171766115457 + 0.00460033018967343im
 -0.0036892439259126704 + 0.025054905770147868im
  -0.007943257210864018 + 0.023625183820638076im
  0.0042928661704610994 + 0.001168497237293148im
  -0.002259932409406792 + 0.025536635166686493im
                        ⋮
  -7.210529034633393e-8 - 1.0816616495191158e-7im
 -2.0910018363390726e-8 + 9.083692358789918e-9im
 -2.0598452412061543e-8 + 1.0406320648650516e-8im
  2.0486442828344457e-9 + 3.5209859104309628e-9im
  -9.711270670731724e-8 - 8.979456730424921e-8im
  -1.850874666452613e-8 + 1.3968038270991013e-8im
  -2.03638

In [12]:
ising = Hamiltonian(σ_z ⊗ σ_z, σ_x)
@time ψ_res = reshape(contract_mps(block_evolve(ψ_mps, ising, t * -1im)), 2^sites)

  0.005370 seconds (134.89 k allocations: 9.754 MiB)


4096-element Vector{ComplexF64}:
     -0.306574384763973 - 0.777853726001379im
   -0.14739219093561268 + 0.0031096975439932517im
   -0.14335337000556025 - 0.02255730886426206im
  -0.003977462164943617 + 0.025277066907463855im
   -0.14335337000556025 - 0.022557308864262007im
  -0.012500776468383358 + 0.0223266859252661im
  -0.008239119316663495 + 0.02380187641636498im
   0.004196913003693655 + 0.0014527790328040637im
   -0.14335337000556028 - 0.022557308864262042im
  -0.012500776468383365 + 0.022326685925266102im
  -0.015985833308352657 + 0.019464468692766627im
   0.003432110995689981 + 0.0028187337213706346im
  -0.008239119316663497 + 0.023801876416364984im
                        ⋮
 -2.1085083024453163e-8 - 1.1957944802171162e-7im
 -2.1065182803480514e-8 - 3.829014195727783e-9im
 -2.1075132913966878e-8 - 5.557258401932856e-11im
  -9.79894595029493e-12 + 3.7161145547493717e-9im
  -6.126579825068748e-8 - 1.0483476083833727e-7im
 -2.1085083024453232e-8 + 3.7178690276891284e-9im
 -2.10751

In [10]:
dot(ψ_res_vect, ψ_res)

0.21694345086338168 + 0.784587895340711im

In [14]:
ψ_mps_high_χ = mps(ψ, 2^(sites ÷ 2))
@time ψ_res_better = reshape(contract_mps(block_evolve(ψ_mps_high_χ, ising, t * -1im)), 2^sites)
#TODO: fix this

LoadError: DimensionMismatch("new dimensions (2, 128) must be consistent with array size 16")